version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'Asia/Tokyo'
    target-branch: 'develop'
    versioning-strategy: 'lockfile-only'
    assignees:
      - 'web-novice-tech'
    commit-message:
      prefix: 'npm'
